// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl5tjetFlujjCQer1lgEsLToumBUFFggI',
    appId: '1:885383775500:web:3c20f9fd59039a5f197529',
    messagingSenderId: '885383775500',
    projectId: 'deta-5c114',
    authDomain: 'deta-5c114.firebaseapp.com',
    storageBucket: 'deta-5c114.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDT09skQ3eSl2bbyl1DWXjaEbLxb9tPjA',
    appId: '1:885383775500:android:05ba3c0722b09b6b197529',
    messagingSenderId: '885383775500',
    projectId: 'deta-5c114',
    storageBucket: 'deta-5c114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-FMb_9krXLFQxnpv3_7mGUN8pUyzlbYE',
    appId: '1:885383775500:ios:2754473e56fdbfbf197529',
    messagingSenderId: '885383775500',
    projectId: 'deta-5c114',
    storageBucket: 'deta-5c114.appspot.com',
    iosClientId: '885383775500-nt0lmj4bkii0qdb1vl7v1qkkqdgahiaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.beta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-FMb_9krXLFQxnpv3_7mGUN8pUyzlbYE',
    appId: '1:885383775500:ios:9e2c7e4fa9df9025197529',
    messagingSenderId: '885383775500',
    projectId: 'deta-5c114',
    storageBucket: 'deta-5c114.appspot.com',
    iosClientId: '885383775500-gqrp4c0vumvj5mqa9ga81e4ialdgetm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.beta.RunnerTests',
  );
}
